version: '3.7'

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    security_opt:
      - no-new-privileges:true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./portainer-data:/data
    ports:
      - "9443:9443"
      - "8000:8000"

  neo4j:
    image: neo4j:5.16.0
    container_name: neo4j
    volumes:
      - $HOME/graph_data/testing:/data
      - ./data:/var/lib/neo4j/import
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_AUTH=neo4j/graphs_@re_c00l
      - NEO4J_PLUGINS=["apoc", "graph-data-science"]
      - apoc.import.file.enabled=true
      - NEO4J_server_memory_pagecache_size=4G
      - NEO4j_server_memory_heap_initial__size=4G
      - NEO4J_server_memory_heap_max__size=8G
      - apoc.export.file.enabled=true

  postgres:
    image: postgres
    container_name: pg_container
    volumes:
      - $HOME/senzing_pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: letmein
      POSTGRES_DB: erkg
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: letmein
